### PR TITLE
Support Japanese holidays.

### PR DESCRIPTION
**Pull request by archseer**
Copied the file over from the ruby library and implemented all the functions. I also had to change the `year_ranges.between` code since it wasn't parsing it properly into a range.

### CODE REVIEW

**Comment by archSeer** [comment]
Hi! I'm not a native speaker, but fluent enough -- I'll try and get it done over the weekend.

The PR is a direct port and could be a bit better I think:

- The between param could be parsed at yaml parse time, instead of doing that every time on comparison time.
- Japan has this notion of substitute holidays, where if a holiday lands on sunday, we still show it on that day, then display a "substitute holiday" on the next working day. It's a bit tricker because it's not monday_if_sunday, because if we have sun, mon, tue as holidays, the substitute holiday lands on wednesday. As such, the majority of these functions expand the previous holiday, then check if a substitute is needed. I think a much better way would be to somehow support a post-processing pass: expand all the holidays, then scan over and generate any necessary substitutions.

I'm probably going to add Korean soon as well, that one requires a bit more work because of the lunar calendar ([ruby implementation](https://github.com/holidays/holidays/blob/c2463483d1289c6b5a493a5de8dab0256ff4436f/lib/holidays/date_calculator/lunar_date.rb), [js implementation](https://github.com/Luavis/moment-lunar/blob/master/moment-lunar.js))

**Comment by kelvinst** [comment]
@archSeer nice! Waiting for your translations then! 👍 

About your other points, I guess you could open another PR for it, this way we can merge and release this one first if that takes too long. 😉

Just one comment on the "substitute holidays", the current implementation has the `observed_date` attribute, which I guess it's pretty much the same: the original date is saved on `date` attribute and the `observed_date` can be a function that returns when this holiday should be observed. Does that solve the problem? Or is it not the same?

Again, thank you for your work! Hope to see more of that soon!

**Review by kelvinst — APPROVED** [review]
Thanks, let's just fix #13 to make sure everything works ;)

As for the changes, everything LGTM

**Comment by kelvinst** [comment]
Translations could be added later, I think we shouldn't care much about them in the first release, IDK. @iurimadeira, WDYT?

**Pull request closed without merging**
