### PR TITLE
Add support for federal reserve holidays

### PR DESCRIPTION
**Pull request by ElijahBrandyberry**
Pretty simple and straightforward commit adding support for Federal Reserve holidays. Since many US businesses are closed on these holidays, it can be an especially useful definition to have.

Let me know if there are any additional changes required for this... I will be happy to tackle them.

### CODE REVIEW

**Comment by ElijahBrandyberry** [comment]
I just updated this PR to resolve merge conflicts... is this ready to be merged in? Let me know if anything else is needed.

**Comment by ElijahBrandyberry** [comment]
@adanselm what needs to be done to get this merged in?

**Comment by adanselm** [comment]
@lukyanov FYI

**Review by lukyanov — APPROVED** [review]

**Comment by lukyanov** [comment]
@ElijahBrandyberry Merged. Thank you!

**Pull request merged**
